### ISSUE TITLE
Related question: do your volume keys work?

### ISSUE THREAD

**Issue by ph818** [alexpdp7/lenovo-thinkpad-x12-detachable-gen1-swap-ctrl-fn-linux#2]
Hello, were you able to get the volume keys to be detected under linux? Not the function keys on the keyboard, but the two hardware keys on the right hand side of the screen?

Since you were able to correct the fn-ctrl layout I wonder if you've found any solution for the volume keys.

**Comment by alexpdp7** [comment]
Oh, sorry, I didn't manage to fix fn-ctrl- I have the USB packet sequence, but I have no way to send it.

Also I've switched to Windows :(

I tested Ubuntu 24.04 and yeah, the volume keys are not working.
